name: Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [19.x] 
        
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install backend dependencies
      run: npm install
      working-directory: ./backend 
    - name: Create .env
      run: echo "${{ secrets.ENV_PRODUCTION }}" > .env
      working-directory: ./backend
    - name: Run migrations
      run: npm run migrate
      working-directory: ./backend
    - name: Generate prisma
      run: npx prisma generate
      working-directory: ./backend      
    - name: Build project
      run: npm run build
      working-directory: ./backend
    - name: Restart service
      run: pm2 restart DriveQuestBackend || pm2 start dist/src/main.js --name DriveQuestBackend
      working-directory: ./backend
    - name: Install frontend dependencies
      run: npm install
    - name: Crreate .env
      run: echo "${{ secrets.FRONTEND_ENV }}" > .env
      working-directory: ./frontend
    - name: Build
      run: npm run build
      working-directory: ./frontend
